### ISSUE TITLE
Issue: new TypeError('app.use() requires a middleware function')

### ISSUE THREAD

**Issue by sameerjha28** [lvasquez/AngularDemo#4]
Issue is as given below while building the project as:

$ node server.js

_throw_ new TypeError('app.use() requires a middleware _function')_

_TypeError:_ app.use() requires a middleware function
    at EventEmitter.use (C:\<folder>\node_modules\express\lib\application.js:210:11)
    at Object.<anonymous> _(C:\<folder>\AngularDemo-master\server.js:16:5)_

This line(16) in server.js is as below

**app.use(multer()); // for parsing multipart/form-data**

**Comment by sameerjha28** [comment]
Comment this line for now, it will work.

This exercise is not including any "multipart/form-data" tasks. So commenting this line wont harm in any way. Code is working now.
